import type { Itinerary, ItineraryPlace } from "../planner/types.ts";

export const SAMPLE_TRIP_ID = "trip_asheville_001";

export function createSampleTrip(): Itinerary {
  return structuredClone({
    trip_id: SAMPLE_TRIP_ID,
    version: 1,
    title: "Asheville Long Weekend",
    timezone: "America/New_York",
    start_date: "2026-04-12",
    end_date: "2026-04-14",
    travelers: [
      { id: "traveler_1", name: "James" },
      { id: "traveler_2", name: "Mina" },
      { id: "traveler_3", name: "Noah" },
    ],
    preferences: {
      pace: "balanced",
      max_walk_minutes: 20,
      preferred_transport_modes: ["drive", "walk"],
      meal_windows: {
        lunch: { start: "11:30", end: "13:30" },
        dinner: { start: "18:00", end: "20:30" },
      },
      must_visit_place_ids: ["place_biltmore"],
      avoid_place_ids: [],
    },
    days: [
      {
        date: "2026-04-12",
        label: "Day 1",
        summary: "Arrival, hotel check-in, downtown walk, and dinner.",
        items: [
          seedItem({
            id: "item_flight_arrival",
            kind: "flight",
            title: "Arrive at AVL",
            start_at: "2026-04-12T09:10:00-04:00",
            end_at: "2026-04-12T10:45:00-04:00",
            status: "confirmed",
            locked: true,
            source: "imported",
            category: "flight",
            place_id: "place_avl",
            tags: ["anchor"],
          }),
          seedItem({
            id: "item_buffer_arrival",
            kind: "buffer",
            title: "Arrival buffer",
            start_at: "2026-04-12T10:45:00-04:00",
            end_at: "2026-04-12T11:15:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "buffer",
            place_id: "place_avl",
          }),
          seedItem({
            id: "item_hotel_checkin",
            kind: "check_in",
            title: "Check in at The Foundry Hotel",
            start_at: "2026-04-12T11:45:00-04:00",
            end_at: "2026-04-12T12:15:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "lodging",
            place_id: "place_foundry",
          }),
          seedItem({
            id: "item_lunch",
            kind: "meal",
            title: "Lunch at White Duck Taco Shop",
            start_at: "2026-04-12T12:30:00-04:00",
            end_at: "2026-04-12T13:30:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "lunch",
            place_id: "place_white_duck",
          }),
          seedItem({
            id: "item_walk_river_arts",
            kind: "activity",
            title: "River Arts District walk",
            start_at: "2026-04-12T14:00:00-04:00",
            end_at: "2026-04-12T16:00:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "sightseeing",
            place_id: "place_river_arts",
          }),
          seedItem({
            id: "item_buffer_hotel",
            kind: "buffer",
            title: "Reset at the hotel",
            start_at: "2026-04-12T16:30:00-04:00",
            end_at: "2026-04-12T18:00:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "buffer",
            place_id: "place_foundry",
          }),
          seedItem({
            id: "item_dinner",
            kind: "meal",
            title: "Dinner at Cúrate",
            start_at: "2026-04-12T18:30:00-04:00",
            end_at: "2026-04-12T20:00:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "dinner",
            place_id: "place_curate",
          }),
        ],
      },
      {
        date: "2026-04-13",
        label: "Day 2",
        summary: "Biltmore day with lunch and a slower evening.",
        items: [
          seedItem({
            id: "item_day2_hotel_depart",
            kind: "transit",
            title: "Leave hotel for Biltmore",
            start_at: "2026-04-13T09:30:00-04:00",
            end_at: "2026-04-13T10:00:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "drive",
            place_id: "place_biltmore",
          }),
          seedItem({
            id: "item_biltmore_visit",
            kind: "activity",
            title: "Biltmore Estate",
            start_at: "2026-04-13T10:00:00-04:00",
            end_at: "2026-04-13T13:00:00-04:00",
            status: "confirmed",
            locked: true,
            source: "user",
            category: "landmark",
            place_id: "place_biltmore",
            tags: ["anchor"],
          }),
          seedItem({
            id: "item_day2_lunch",
            kind: "meal",
            title: "Lunch at Stable Cafe",
            start_at: "2026-04-13T13:20:00-04:00",
            end_at: "2026-04-13T14:10:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "lunch",
            place_id: "place_stable_cafe",
          }),
          seedItem({
            id: "item_bookshop",
            kind: "activity",
            title: "Coffee and bookshop stop",
            start_at: "2026-04-13T15:00:00-04:00",
            end_at: "2026-04-13T16:45:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "shopping",
            place_id: "place_battery_bookshop",
          }),
          seedItem({
            id: "item_day2_buffer",
            kind: "buffer",
            title: "Reset at hotel",
            start_at: "2026-04-13T17:00:00-04:00",
            end_at: "2026-04-13T18:45:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "buffer",
            place_id: "place_foundry",
          }),
          seedItem({
            id: "item_day2_dinner",
            kind: "meal",
            title: "Dinner in West Asheville",
            start_at: "2026-04-13T19:00:00-04:00",
            end_at: "2026-04-13T20:30:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "dinner",
            place_id: "place_admiral",
          }),
        ],
      },
      {
        date: "2026-04-14",
        label: "Day 3",
        summary: "Brunch, check-out, and a gentle departure day.",
        items: [
          seedItem({
            id: "item_day3_brunch",
            kind: "meal",
            title: "Brunch at All Day Darling",
            start_at: "2026-04-14T08:30:00-04:00",
            end_at: "2026-04-14T10:00:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "breakfast",
            place_id: "place_all_day_darling",
          }),
          seedItem({
            id: "item_day3_checkout",
            kind: "check_out",
            title: "Pack and check out",
            start_at: "2026-04-14T10:30:00-04:00",
            end_at: "2026-04-14T11:45:00-04:00",
            status: "confirmed",
            locked: true,
            source: "user",
            category: "lodging",
            place_id: "place_foundry",
          }),
          seedItem({
            id: "item_day3_park",
            kind: "activity",
            title: "Riverside park walk",
            start_at: "2026-04-14T12:00:00-04:00",
            end_at: "2026-04-14T13:45:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "park",
            place_id: "place_carrier_park",
          }),
          seedItem({
            id: "item_day3_drive_airport",
            kind: "transit",
            title: "Head toward AVL",
            start_at: "2026-04-14T14:15:00-04:00",
            end_at: "2026-04-14T15:15:00-04:00",
            status: "suggested",
            locked: false,
            source: "ai",
            category: "drive",
            place_id: "place_avl",
          }),
          seedItem({
            id: "item_day3_airport_buffer",
            kind: "buffer",
            title: "Airport buffer",
            start_at: "2026-04-14T15:30:00-04:00",
            end_at: "2026-04-14T18:15:00-04:00",
            status: "confirmed",
            locked: true,
            source: "imported",
            category: "buffer",
            place_id: "place_avl",
          }),
        ],
      },
    ],
    places: createSamplePlaceCatalog(),
    routes: [],
    conflicts: [],
    markdown_sections: [],
    change_log: [
      {
        id: "change_seed",
        timestamp: "2026-03-30T18:55:00-04:00",
        actor: "assistant",
        summary: "Seeded the sample Asheville itinerary for local workspace testing.",
        command_ids: [],
      },
    ],
  } satisfies Itinerary);
}

export function createSamplePlaceCatalog(): ItineraryPlace[] {
  return structuredClone([
    place({
      place_id: "place_avl",
      provider: "manual",
      name: "Asheville Regional Airport",
      category: "airport",
      lat: 35.4362,
      lng: -82.5418,
      address: "61 Terminal Dr, Fletcher, NC 28732",
    }),
    place({
      place_id: "place_foundry",
      provider: "manual",
      name: "The Foundry Hotel Asheville",
      category: "hotel",
      lat: 35.5985,
      lng: -82.5498,
      address: "51 S Market St, Asheville, NC 28801",
    }),
    place({
      place_id: "place_white_duck",
      provider: "manual",
      name: "White Duck Taco Shop",
      category: "restaurant",
      lat: 35.5794,
      lng: -82.5919,
      address: "388 Riverside Dr, Asheville, NC 28801",
      rating: 4.7,
      price_level: 2,
      opening_hours: [
        { weekday: "sunday", open: "11:00", close: "21:00" },
        { weekday: "monday", open: "11:00", close: "21:00" },
      ],
    }),
    place({
      place_id: "place_river_arts",
      provider: "manual",
      name: "River Arts District",
      category: "landmark",
      lat: 35.5798,
      lng: -82.5882,
      address: "Asheville, NC 28801",
    }),
    place({
      place_id: "place_curate",
      provider: "manual",
      name: "Cúrate",
      category: "restaurant",
      lat: 35.5941,
      lng: -82.5511,
      address: "13 Biltmore Ave, Asheville, NC 28801",
      rating: 4.7,
      price_level: 4,
      opening_hours: [
        { weekday: "sunday", open: "17:00", close: "19:30" },
        { weekday: "monday", open: "17:00", close: "21:00" },
      ],
    }),
    place({
      place_id: "place_biltmore",
      provider: "manual",
      name: "Biltmore Estate",
      category: "landmark",
      lat: 35.5404,
      lng: -82.5528,
      address: "1 Lodge St, Asheville, NC 28803",
      rating: 4.8,
      price_level: 4,
      opening_hours: [
        { weekday: "monday", open: "09:00", close: "17:00" },
      ],
    }),
    place({
      place_id: "place_stable_cafe",
      provider: "manual",
      name: "Stable Cafe",
      category: "restaurant",
      lat: 35.5409,
      lng: -82.5515,
      address: "1 Approach Rd, Asheville, NC 28803",
      rating: 4.4,
      price_level: 2,
      opening_hours: [
        { weekday: "monday", open: "11:00", close: "15:00" },
      ],
    }),
    place({
      place_id: "place_battery_bookshop",
      provider: "manual",
      name: "Battery Park Book Exchange",
      category: "shopping",
      lat: 35.5969,
      lng: -82.5539,
      address: "1 Page Ave #101, Asheville, NC 28801",
      rating: 4.8,
      price_level: 2,
      opening_hours: [
        { weekday: "monday", open: "11:00", close: "22:00" },
      ],
    }),
    place({
      place_id: "place_admiral",
      provider: "manual",
      name: "The Admiral",
      category: "restaurant",
      lat: 35.5787,
      lng: -82.5841,
      address: "400 Haywood Rd, Asheville, NC 28806",
      rating: 4.6,
      price_level: 3,
      opening_hours: [
        { weekday: "monday", open: "17:00", close: "22:00" },
      ],
    }),
    place({
      place_id: "place_all_day_darling",
      provider: "manual",
      name: "All Day Darling",
      category: "restaurant",
      lat: 35.5867,
      lng: -82.5613,
      address: "102 Montford Ave, Asheville, NC 28801",
      rating: 4.6,
      price_level: 2,
      opening_hours: [
        { weekday: "tuesday", open: "08:00", close: "15:00" },
      ],
    }),
    place({
      place_id: "place_carrier_park",
      provider: "manual",
      name: "Carrier Park",
      category: "park",
      lat: 35.5714,
      lng: -82.5896,
      address: "220 Amboy Rd, Asheville, NC 28806",
      rating: 4.7,
      opening_hours: [
        { weekday: "tuesday", open: "07:00", close: "20:30" },
      ],
    }),
    place({
      place_id: "place_foothills_smokehouse",
      provider: "manual",
      name: "Foothills Smokehouse",
      category: "restaurant",
      lat: 35.5928,
      lng: -82.5531,
      address: "18 Broadway St, Asheville, NC 28801",
      rating: 4.8,
      price_level: 3,
      opening_hours: [
        { weekday: "sunday", open: "17:30", close: "22:00" },
        { weekday: "monday", open: "17:30", close: "22:00" },
      ],
    }),
    place({
      place_id: "place_blue_ridge_tavern",
      provider: "manual",
      name: "Blue Ridge Tavern",
      category: "restaurant",
      lat: 35.5956,
      lng: -82.5521,
      address: "29 Biltmore Ave, Asheville, NC 28801",
      rating: 4.5,
      price_level: 2,
      opening_hours: [
        { weekday: "sunday", open: "17:00", close: "23:00" },
        { weekday: "monday", open: "17:00", close: "23:00" },
      ],
    }),
    place({
      place_id: "place_downtown_bistro",
      provider: "manual",
      name: "Downtown Bistro",
      category: "restaurant",
      lat: 35.5961,
      lng: -82.5518,
      address: "31 College St, Asheville, NC 28801",
      rating: 4.7,
      price_level: 3,
      opening_hours: [
        { weekday: "sunday", open: "17:00", close: "22:30" },
        { weekday: "monday", open: "17:00", close: "22:30" },
      ],
    }),
  ] satisfies ItineraryPlace[]);
}

function seedItem(input: Record<string, unknown>) {
  return {
    tags: [],
    validation_conflict_ids: [],
    ...input,
  };
}

function place(input: ItineraryPlace): ItineraryPlace {
  return input;
}
